export const CONSTANTS = {
  seoTags: [
    { name: "keywords", content: "Angular SEO, Angular Universal" },
    { name: "keywords", content: "bhaifinance" },
    { name: "keywords", content: "Blockchain" },
    { name: "keywords", content: "Finance" },
    { name: "keywords", content: "wallet" },
    { name: "keywords", content: "crypto" },
    { name: "keywords", content: "payment" },
    { name: "keywords", content: "Bhai" },
    { name: "keywords", content: "web3" },
    { name: "keywords", content: "tokens" },
    { name: "keywords", content: "exchanges" },
    { name: "keywords", content: "bills" },
    { name: "keywords", content: "utilities" },
    { name: "keywords", content: "bitcoin" },
    { name: "keywords", content: "ethereum" },
    { name: "keywords", content: "bills" },

    { name: "keywords", content: "Bitcoin" },
    { name: "keywords", content: "Ethereum" },
    { name: "keywords", content: "Ripple (XRP)" },
    { name: "keywords", content: "Litecoin" },
    { name: "keywords", content: "Cardano (ADA)" },
    { name: "keywords", content: "Stellar (XLM)" },
    { name: "keywords", content: "Polkadot (DOT)" },
    { name: "keywords", content: "Cryptocurrency News" },
    { name: "keywords", content: "Crypto Exchanges" },
    { name: "keywords", content: "Wallets" },
    { name: "keywords", content: "Trading Strategies" },
    { name: "keywords", content: "Cryptocurrency Portfolios" },
    { name: "keywords", content: "Crypto Market Analysis" },
    { name: "keywords", content: "Tokenomics" },
    { name: "keywords", content: "Blockchain Explained" },
    { name: "keywords", content: "Smart Contracts" },
    { name: "keywords", content: "Blockchain Development" },
    { name: "keywords", content: "Consensus Algorithms" },
    { name: "keywords", content: "Blockchain Security" },
    { name: "keywords", content: "Cryptocurrency Laws" },
    { name: "keywords", content: "Regulatory Compliance" },
    { name: "keywords", content: "IRS Cryptocurrency Taxation" },
    { name: "keywords", content: "Latest Crypto Updates" },
    { name: "keywords", content: "Cryptocurrency Market Trends" },
    { name: "keywords", content: "Crypto Price Analysis" },
    { name: "keywords", content: "Cryptocurrency Events" },
    { name: "keywords", content: "Market Volatility" },
    { name: "keywords", content: "Crypto Market News" },
    { name: "keywords", content: "Hardware Wallets" },
    { name: "keywords", content: "Software Wallets" },
    { name: "keywords", content: "Mobile Wallets" },
    { name: "keywords", content: "Cold Wallets" },
    { name: "keywords", content: "Hot Wallets" },
    { name: "keywords", content: "Wallet Security" },
    { name: "keywords", content: "Cryptocurrency Trading Platforms" },
    { name: "keywords", content: "Trading Strategies" },
    { name: "keywords", content: "Technical Analysis" },
    { name: "keywords", content: "Candlestick Patterns" },
    { name: "keywords", content: "Trading Bots" },
    { name: "keywords", content: "Risk Management" },
    { name: "keywords", content: "Alternative Cryptocurrencies" },
    { name: "keywords", content: "Altcoin Investing" },
    { name: "keywords", content: "Altcoin Reviews" },
    { name: "keywords", content: "Altcoin Analysis" },
    { name: "keywords", content: "Altcoin News" },
    { name: "keywords", content: "Best Altcoins" },
    { name: "keywords", content: "Bitcoin Mining" },
    { name: "keywords", content: "Ethereum Mining" },
    { name: "keywords", content: "Mining Hardware" },
    { name: "keywords", content: "Mining Pools" },
    { name: "keywords", content: "Mining Profitability" },
    { name: "keywords", content: "Crypto Scams" },
    { name: "keywords", content: "Phishing Attacks" },
    { name: "keywords", content: "Two-Factor Authentication " },
    { name: "keywords", content: "Secure Passwords" },
    { name: "keywords", content: "Security Best Practices" },
    { name: "keywords", content: "Hardware Security Modules" },
    { name: "keywords", content: "Beginner's Guides" },
    { name: "keywords", content: "Crypto Glossary" },
    { name: "keywords", content: "How to Buy Crypto" },
    { name: "keywords", content: "How to Store Crypto" },
    { name: "keywords", content: "Crypto FAQs" },
    { name: "keywords", content: "Cryptocurrency Tutorials" },
    { name: "keywords", content: "Cryptocurrency Conferences" },
    { name: "keywords", content: "AMAs" },
    { name: "keywords", content: "Crypto Summits" },
    { name: "keywords", content: "Crypto Networking" },
    { name: "keywords", content: "Cryptocurrency Wallets" },
    { name: "keywords", content: "Digital Wallets" },
    { name: "keywords", content: "Secure Wallets" },
    { name: "keywords", content: "Crypto Storage" },
    { name: "keywords", content: "Wallet Services" },
    { name: "keywords", content: "Mobile Wallets" },
    { name: "keywords", content: "Desktop Wallets" },
    { name: "keywords", content: "Bitcoin Wallet" },
    { name: "keywords", content: "Ethereum Wallet" },
    { name: "keywords", content: "Ripple (XRP) Wallet" },
    { name: "keywords", content: "Litecoin Wallet" },
    { name: "keywords", content: "Bitcoin Cash Wallet" },
    { name: "keywords", content: "Cardano (ADA) Wallet" },
    { name: "keywords", content: "Stellar (XLM) Wallet" },
    { name: "keywords", content: "Multi-Currency Wallet" },
    { name: "keywords", content: "Private Keys" },
    { name: "keywords", content: "Public Addresses" },
    { name: "keywords", content: "Seed Phrases" },
    { name: "keywords", content: "Cold Storage" },
    { name: "keywords", content: "Hot Wallets" },
    { name: "keywords", content: "Wallet Security" },
    { name: "keywords", content: "Send Cryptocurrency" },
    { name: "keywords", content: "Receive Cryptocurrency" },
    { name: "keywords", content: "Transaction History" },
    { name: "keywords", content: "Transaction Fees" },
    { name: "keywords", content: "Confirmations" },
    { name: "keywords", content: "Blockchain Explorer" },
    { name: "keywords", content: "Paper Wallets" },
    { name: "keywords", content: "Custodial Wallets" },
    { name: "keywords", content: "Non-Custodial Wallets" },
    { name: "keywords", content: "Wallet Encryption" },
    { name: "keywords", content: "Biometric Authentication" },
    { name: "keywords", content: "Privacy Features" },
    { name: "keywords", content: "Multi-Signature Wallets" },
    { name: "keywords", content: "Backup and Recovery" },
    { name: "keywords", content: "Secure Storage" },
    { name: "keywords", content: "Compare Wallets" },
    { name: "keywords", content: "Best Crypto Wallets" },
    { name: "keywords", content: "Wallet Reviews" },
    { name: "keywords", content: "Wallet Pros and Cons" },
    { name: "keywords", content: "Wallet Comparison Chart" },
    { name: "keywords", content: "How to Create a Wallet" },
    { name: "keywords", content: "Setting Up a Wallet" },
    { name: "keywords", content: "Wallet Registration" },
    { name: "keywords", content: "Funding Your Wallet" },
    { name: "keywords", content: "Sending Your First Transaction" },
    { name: "keywords", content: "Wallet Updates" },
    { name: "keywords", content: "Wallet Backups" },
    { name: "keywords", content: "Wallet Security Tips" },
    { name: "keywords", content: "Wallet Troubleshooting" },
    { name: "keywords", content: "Wallet Recovery" },
    { name: "keywords", content: "What is Cryptocurrency?" },
    { name: "keywords", content: "How Wallets Work" },
    { name: "keywords", content: "Cryptocurrency Basics" },
    { name: "keywords", content: "Wallet FAQs" },
    { name: "keywords", content: "Wallet Guides" },
    { name: "keywords", content: "Wallet Help Center" },
    { name: "keywords", content: "Contact Support" },
    { name: "keywords", content: "Frequently Asked Questions" },
    { name: "keywords", content: "Wallet Assistance" },
    { name: "keywords", content: "Troubleshooting" },
    { name: "keywords", content: "Cryptocurrency Wallet Updates" },
    { name: "keywords", content: "Wallet Security News" },
    { name: "keywords", content: "Wallet Technology News" },
    { name: "keywords", content: "Crypto Wallet Innovations" },
    { name: "keywords", content: "Bhai Finance" },
    { name: "keywords", content: "bhai finance" },
    { name: "keywords", content: "BhaiFinance" },
    { name: "keywords", content: "bhaifinance" },
    { name: "keywords", content: "Crypto" },
  ],
};
